CREATE DATABASE BT6;

USE BT6;

CREATE TABLE ANIMAL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(20),
    MAXIMUM_MILK_GIVEN INT,
    SPEAK VARCHAR(20),
    QUANTITY INT,
)

INSERT INTO ANIMAL
VALUES ('CUU',5,'CUU!','0')
INSERT INTO ANIMAL
VALUES ('BO',20,'BO!','0')
INSERT INTO ANIMAL
VALUES ('DE',10,'DE!','0')